spring:
  ##################freemarker config begin#################
  freemarker:
    #后缀
    suffix: .ftl
    #前缀
    #prefix: /
    #关闭缓存，建议开发环境设置为false，生成环境设置为true
    cache: false
    charset: utf-8
    content-type: text/html
    #设定模板的加载路径,多个以逗号分隔，默认: ["classpath:/templates/"]
    template-loader-path: classpath:/templates
    #是否检查templates路径是否存在
    check-template-location: true
    #指定HttpServletRequest的属性是否可以覆盖controller的model的同名项
    allow-request-override: false
    #指定HttpSession的属性是否可以覆盖controller的model的同名项
    allow-session-override: false
    #设定所有request的属性在merge到模板的时候，是否要都添加到model中
    #把contextPath暴露给freemaker，前端可以通过${request.getContextPath()} 来获取上下文路径
    expose-request-attributes: true
    #设定所有HttpSession的属性在merge到模板的时候，是否要都添加到model中
    expose-session-attributes: true
    #设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
    expose-spring-macro-helpers: false
    #指定RequestContext属性的名
    request-context-attribute: request
    settings:
#    spring.freemarker.settings:
      default_encoding: UTF-8
      output_encoding: UTF-8
      locale: zh_CN
      number_format: 0.##
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      #可以满足一般需要。默认情况变量为null则替换为空字符串，如果需要自定义，写上${empty!"EmptyValue of fbysss"}的形式即可
      classic_compatible: true
      template_exception_handler: html_debug
  ##################freemarker config end#################

  ##################redis config begin  ##################
  redis:
    #redis数据库名称(默认为0)
    database: 0
    #Matser的ip地址
    host: 127.0.0.1
    #redis服务器密码(默认为空)
    password:
    #redis服务器连接端口号
    port: 6379
    #客户端超时时间单位是毫秒 默认是2000
    timeout: 60000
    #################redis线程池设置#################
    #redis连接池设置
    pool:
      #连接池中的最大空闲连接
      maxIdle: 8
      #连接池中的最小空闲连接
      minIdle: 0
      # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
      #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
      maxActive: 8
      #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
#      redis.maxTotal: 8
      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
      #连接池最大阻塞等待时间(使用负值表示没有限制)
      maxWait: -1
      #redis集群配置
#      spring.redis.cluster.nodes=192.168.177.128:7001,192.168.177.128:7002,192.168.177.128:7003,192.168.177.128:7004,192.168.177.128:7005,192.168.177.128:7006
#      spring.redis.cluster.max-redirects=3
  ##################redis config end#  #################

  ##################datasource config begin #################
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rent?useUnicode=true&characterEncoding=utf8
      username: root
      password:

      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait : 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      #用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: select 1 FROM DUAL
      #申请连接的时候检测
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
      #监控统计用的filter:stat 日志用的filter:log4j 防御SQL注入的filter:wall
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
  ##################datasource config end #################

 wx:
   qy:
     agent:
       id: 1000002
     corp:
       id: ww170cb031844a5400
       secret: bi3mQAWY1hIVcGhOhAYdW83LQAVG-fuYQAJe5OAjyy0
     report:
       url: https://edcd.evergrande.com/edc_wx/msgPush.html?planID=%s
 jpush:
   server: http://notify.eafservice.evergrande.com
   key: c1a786a57a59620a86fce314
   secret: 2b39cd397064cfbad5b055ab