server:
  port: 8083
  session:
    timeout: 3600
  context-path: /rent
  tomcat:
    uri-encoding: utf-8
  error:
    path: /error

#springboot 监控
management:
  port: 54001
  health:
    mail:
      enabled: false

spring:
  profiles:
    active: dev
  session:
    store-type: redis
  #自定义静态资源
  mvc:
    static-path-pattern: /static/**
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  config: classpath:logback-spring.xml

 ##################mybatis config begin  #################
mybatis:
  #实体类所在包
  type-aliases-package: com.scrats.rent.entity
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    mapUnderscoreToCamelCase: true
    map-underscore-to-camel-case: true
    #是否启用下划线与驼峰式命名规则的映射（如first_name => firstName

#通用mapper
mapper:
  mappers: com.scrats.rent.base.mapper.BaseMapper
  not-empty: false
  identity: MYSQL

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql